#!/bin/bash

IFS='.' read -ra ADDR <<< "$1"
COUNT=0
pro=""
eth=""
ValidIP=1
if [[ "$3" = "sudo" ]]; then
pro="sudo"
fi
if [[ "$2" = *ens* ]]; then
	eth=$2
else
	eth="eth0"
fi

echo -e "\n\nValidating ip address..."
for i in "${ADDR[@]}"; do
	if [[ ($i -gt 255) && ($i -lt 0) ]]; then
		ValidIP=0
	fi
	COUNT=$((COUNT+1))
done

StrLen=$(echo -n $1 | wc -m)

if [[ ($ValidIP -ne 1) || ($COUNT -ne 4) ]]; then
	echo "Please enter a valid IP Address."
	exit 1
fi
echo "$sudo"
echo "Linking ethernet..." 
echo `"$pro" ifconfig "$eth" up`
sleep 5
echo "Link complete!"
echo "Setting up ethernet..."
echo `$pro ip link set "$eth" up`
echo "Setup complete!"
echo "Setting IP Address..."
echo `$pro ifconfig "$eth" $1`
echo `$pro ip address add $1 dev "$eth"`
echo "IP setup complete!"
echo "Ethernet has been setup for IP - $1"
